ADD decryptor utils
xBacked-DAO/xbacked-sdk pull request #58
Opened 2022-09-30 00:23 UTC by JCastrejonE

2022-09-30 00:35 UTC, AwolDes requested changes

2022-09-30 00:35 UTC, AwolDes commented on src/DecryptorUtils.ts
> +(async () => {
I think if we import this util, and include this block of code, it will run on import. Can we remove it & document it elsewhere?

2022-10-04 18:54 UTC, Jesulonimi21 reviewed
Great work @JCastrejonE just one comment

2022-10-04 18:54 UTC, Jesulonimi21 commented on src/DecryptorUtils.ts
> +})();
Do we want to put this in the examples directory?

2022-10-05 17:52 UTC, merged